def seed_occupations

    occupations = Occupation.create([
        { name: 'Carpintero/a' },
    { name: 'Fontanero/a' },
    { name: 'Montador/a de cristales y vidrios' },
    { name: 'Operador de atención al cliente' },
    { name: 'Creador/a de contenido digital' },
    { name: 'Pintor/a' },
    { name: 'Auxiliar contable' },
    { name: 'Cerrajero/a' },
    { name: 'Operario/a de logística' },
    { name: 'Panadero/a' },
    { name: 'Mecánico/a' },
    { name: 'Cultor/a de belleza' },
    { name: 'Peluquero/a' },
    { name: 'Peluquero/a de mascotas' },
    { name: 'Carnicero/a' },
    { name: 'Joyero/a' },
    { name: 'Zapatero/a' },
    { name: 'Soldador/a' },
    { name: 'Auxiliar administrativo' },
    { name: 'Chapista de vehículos' },
    { name: 'Relojero/a' },
    { name: 'Barnizador' },
    { name: 'Lutier' },
    { name: 'Conductor/a' },
    { name: 'Camarero/a' },
    { name: 'Alfarero/a' },
    { name: 'Ebanista' },
    { name: 'Albañil' },
    { name: 'Herrero' },
    { name: 'Tatuador/a' },
    { name: 'Maquillador/a' },
    { name: 'Auxiliar de jardinería' },
    { name: 'Gestor/a comercial' },
    { name: 'Instalador/a de climatización' },
    { name: 'Transportista' },
    { name: 'Sastre' },
    { name: 'Pescadero/a' },
    { name: 'Cocinero/a' },
    { name: 'Serigrafista' },
    { name: 'Tapicero/a' },
    { name: 'Repostero/a' },
    { name: 'Decorador/a de interiores' },
    { name: 'Auxiliar de jardín de infancia' },
    { name: 'Electricista' },
    { name: 'Marroquinero/a' },
    { name: 'Estibador/a' },
    { name: 'Médico/a' },
    { name: 'Nutricionista' },
    { name: 'Desarrollador/a web' },
    { name: 'Oftalmólogo/a' },
    { name: 'Diseñador/a gráfico' },
    { name: 'Psicólogo/a' },
    { name: 'Odontólogo/a' },
    { name: 'Maestro de educación especial' },
    { name: 'Logopeda' },
    { name: 'Abogado/a' },
    { name: 'Economista' },
    { name: 'Especialista en E-commerce' },
    { name: 'Periodista' },
    { name: 'Músico/a' },
    { name: 'Veterinario/a' },
    { name: 'Ingeniero/a en telecomunicaciones' },
    { name: 'Asesor/a financiero' },
    { name: 'Piloto de aeronaves' },
    { name: 'Juez/a' },
    { name: 'Fisioterapeuta' },
    { name: 'Administrador/a de empresas' },
    { name: 'Politólogo/a' },
    { name: 'Desarrollador/a de videojuegos' },
    { name: 'Enfermero/a' },
    { name: 'Director/a de museos' },
    { name: 'Trabajador/a social' },
    { name: 'Historiador/a' },
    { name: 'Notario/a' },
    { name: 'Técnico/a en recursos humanos' },
    { name: 'Fotógrafo/a' },
    { name: 'Biólogo/a' },
    { name: 'Compositor/a musical' },
    { name: 'Arquitecto de computación' },
    { name: 'Especialista en turismo y comercio' },
    { name: 'Entrenador' },
    { name: 'Investigador/a criminológico/a' },
    { name: 'Terapeuta ocupacional' },
    { name: 'Geógrafo/a' },
    { name: 'Pedagogo/a' },
    { name: 'Farmacéutico/a' },
    { name: 'Estadístico/a' },
    { name: 'Operador/a turístico' },
    { name: 'Diseñador/a de moda' },
    { name: 'Perito en lingüística forense' },
    { name: 'Gestor medioambiental' },
    { name: 'Otra profesión u oficio' },
    ])

end